### ISSUE TITLE
Update Angular CLI

### ISSUE THREAD

**Issue by kasaharu** [kasaharu/annictor#53]
## 対応内容
- Angular CLI のアップデートをする

```
$ yarn add --dev @angular/cli@^6.0.1
```

- マイグレーションを実施
```
$ ng update @angular/cli --migrate-only --from=1.7.3
```

## 学習内容

- https://lacolaco.hatenablog.com/entry/2018/04/09/070000

**Comment by kasaharu** [comment]
- `yarn test` でエラー発生

```
ERROR in ./src/app/app.component.scss
Module build failed:
@import 'mixin';
^
      File to import not found or unreadable: mixin.
      in /Users/watarukasahara/work/annictor/src/app/app.component.scss (line 1, column 1)
 @ ./src/app/app.component.ts 18:21-52
 @ ./src/app/app.component.spec.ts
 @ ./src sync \.spec\.ts$
 @ ./src/test.ts
```

**Comment by kasaharu** [comment]
* `yarn test` の `--single-run` オプションが効かなくなったので `--watch=false` で代替

**Comment by kasaharu** [comment]
* `yarn build` で下記エラーが発生

```
chunk {0} runtime.6afe30102d8fe7337431.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.e2ee1f7e974858d37595.css (styles) 45.3 kB [initial] [rendered]
chunk {2} polyfills.3a2cc09f9515a07bf722.js (polyfills) 59.1 kB [initial] [rendered]
chunk {3} main.555dba2cd512935e98e5.js (main) 490 kB [initial] [rendered]
Error: Expected to find an ngsw-config.json configuration file in the /Users/watarukasahara/work/annictor folder. Either provide one or disable Service Worker in your angular.json configuration file.
Error: Error: Expected to find an ngsw-config.json configuration file in the /Users/watarukasahara/work/annictor folder. Either provide one or disable Service Worker in your angular.json configuration file.
    at SwitchMapSubscriber.host.exists.pipe.operators_1.switchMap.exists [as project] (/Users/watarukasahara/work/annictor/node_modules/@angular-devkit/build-angular/src/angular-cli-files/utilities/service-worker/index.js:91:19)
    at SwitchMapSubscriber._next (/Users/watarukasahara/work/annictor/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/switchMap.js:90:27)
    at SwitchMapSubscriber.Subscriber.next (/Users/watarukasahara/work/annictor/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:103:18)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/Users/watarukasahara/work/annictor/node_modules/@angular-devkit/core/node/host.js:197:17)
    at Observable._trySubscribe (/Users/watarukasahara/work/annictor/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:177:25)
    at Observable.subscribe (/Users/watarukasahara/work/annictor/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:162:93)
    at SwitchMapOperator.call (/Users/watarukasahara/work/annictor/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/switchMap.js:69:23)
    at Observable.subscribe (/Users/watarukasahara/work/annictor/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:159:22)
    at MapOperator.call (/Users/watarukasahara/work/annictor/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/map.js:62:23)
    at Observable.subscribe (/Users/watarukasahara/work/annictor/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:159:22)
    at SwitchMapOperator.call (/Users/watarukasahara/work/annictor/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/switchMap.js:69:23)
    at Observable.subscribe (/Users/watarukasahara/work/annictor/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:159:22)
    at SwitchMapOperator.call (/Users/watarukasahara/work/annictor/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/switchMap.js:69:23)
    at Observable.subscribe (/Users/watarukasahara/work/annictor/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:159:22)
    at SwitchMapOperator.call (/Users/watarukasahara/work/annictor/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/switchMap.js:69:23)
    at Observable.subscribe (/Users/watarukasahara/work/annictor/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:159:22)
```

**Comment by kasaharu** [comment]
#54 で対応済み
